version : '2.3'
services:
  denso_ros_melodic:
    build : .
    image : denso_ros_melodic:latest
    container_name : denso_ros_melodic
    runtime: nvidia
    ports : 
    - "5555:8888"
    volumes:
      - ./:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment :
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA-VISIBLE-DEVICE=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    tty : true
    stdin_open : true